#pragma once

#include <QtCore/QtGlobal>

#if defined(QTMATERIAL3_THEME_LIBRARY)
#  define QTMATERIAL3_THEME_EXPORT Q_DECL_EXPORT
#else
#  define QTMATERIAL3_THEME_EXPORT Q_DECL_IMPORT
#endif

#if defined(QTMATERIAL3_LEGACY_LIBRARY)
#  define QTMATERIAL3_LEGACY_EXPORT Q_DECL_EXPORT
#else
#  define QTMATERIAL3_LEGACY_EXPORT Q_DECL_IMPORT
#endif
