#pragma once

#include <QtCore/QtGlobal>

#if defined(QTMATERIAL3_STATIC)

#  define QTMATERIAL3_THEME_EXPORT
#  define QTMATERIAL3_CORE_EXPORT
#  define QTMATERIAL3_SPECS_EXPORT
#  define QTMATERIAL3_EFFECTS_EXPORT
#  define QTMATERIAL3_WIDGETS_EXPORT

# define QTMATERIAL3_INTEGRATION_EXPORT

#else

#  if defined(QTMATERIAL3_THEME_LIBRARY)
#    define QTMATERIAL3_THEME_EXPORT Q_DECL_EXPORT
#  else
#    define QTMATERIAL3_THEME_EXPORT Q_DECL_IMPORT
#  endif

#  if defined(QTMATERIAL3_CORE_LIBRARY)
#    define QTMATERIAL3_CORE_EXPORT Q_DECL_EXPORT
#  else
#    define QTMATERIAL3_CORE_EXPORT Q_DECL_IMPORT
#  endif

#  if defined(QTMATERIAL3_SPECS_LIBRARY)
#    define QTMATERIAL3_SPECS_EXPORT Q_DECL_EXPORT
#  else
#    define QTMATERIAL3_SPECS_EXPORT Q_DECL_IMPORT
#  endif

#  if defined(QTMATERIAL3_EFFECTS_LIBRARY)
#    define QTMATERIAL3_EFFECTS_EXPORT Q_DECL_EXPORT
#  else
#    define QTMATERIAL3_EFFECTS_EXPORT Q_DECL_IMPORT
#  endif

#  if defined(QTMATERIAL3_WIDGETS_LIBRARY)
#    define QTMATERIAL3_WIDGETS_EXPORT Q_DECL_EXPORT
#  else
#    define QTMATERIAL3_WIDGETS_EXPORT Q_DECL_IMPORT
#  endif

# if defined(QTMATERIAL3_INTEGRATION_LIBRARY)
#  define QTMATERIAL3_INTEGRATION_EXPORT Q_DECL_EXPORT
# else
#  define QTMATERIAL3_INTEGRATION_EXPORT Q_DECL_IMPORT
# endif

#endif

#ifndef QTMATERIAL3_DISABLE_DEPRECATED_BEFORE
# define QTMATERIAL3_DISABLE_DEPRECATED_BEFORE 0
#endif

#ifndef QTMATERIAL3_DEPRECATED
# define QTMATERIAL3_DEPRECATED Q_DECL_DEPRECATED
#endif

#ifndef QTMATERIAL3_DEPRECATED_X
# define QTMATERIAL3_DEPRECATED_X(message) Q_DECL_DEPRECATED_X(message)
#endif
