#pragma once

#include <QtCore/QtGlobal>

#if defined(QTMATERIAL3_THEME_LIBRARY)
#  define QTMATERIAL3_THEME_EXPORT Q_DECL_EXPORT
#else
#  define QTMATERIAL3_THEME_EXPORT Q_DECL_IMPORT
#endif

#if defined(QTMATERIAL3_LEGACY_LIBRARY)
#  define QTMATERIAL3_LEGACY_EXPORT Q_DECL_EXPORT
#else
#  define QTMATERIAL3_LEGACY_EXPORT Q_DECL_IMPORT
#endif

#if defined(QTMATERIAL3_CORE_LIBRARY)
#  define QTMATERIAL3_CORE_EXPORT Q_DECL_EXPORT
#else
#  define QTMATERIAL3_CORE_EXPORT Q_DECL_IMPORT
#endif

#if defined(QTMATERIAL3_SPECS_LIBRARY)
#  define QTMATERIAL3_SPECS_EXPORT Q_DECL_EXPORT
#else
#  define QTMATERIAL3_SPECS_EXPORT Q_DECL_IMPORT
#endif

#if defined(QTMATERIAL3_EFFECTS_LIBRARY)
#  define QTMATERIAL3_EFFECTS_EXPORT Q_DECL_EXPORT
#else
#  define QTMATERIAL3_EFFECTS_EXPORT Q_DECL_IMPORT
#endif

#if defined(QTMATERIAL3_WIDGETS_LIBRARY)
#  define QTMATERIAL3_WIDGETS_EXPORT Q_DECL_EXPORT
#else
#  define QTMATERIAL3_WIDGETS_EXPORT Q_DECL_IMPORT
#endif
