[build-system]
requires = [
  "scikit-build-core>=0.11",
  "cmake>=3.22",
  "ninja>=1.10",
  "PySide6==6.6.3",
  "shiboken6==6.6.3",
  "shiboken6-generator==6.6.3",
]
build-backend = "scikit_build_core.build"

[project]
name = "qtmaterial3-widgets"
version = "1.0.0"
description = "Qt6/PySide6 bindings for qt-material3-widget"
requires-python = ">=3.10,<3.13"
license = { text = "LGPL-3.0-only" }
authors = [{ name = "faudard" }]
dependencies = ["PySide6==6.6.3"]

[tool.scikit-build]
cmake.source-dir = "../.."
wheel.install-dir = ""
build-dir = "build/{wheel_tag}"

[tool.scikit-build.cmake.define]
QTMATERIAL3_BUILD_PYTHON_BINDINGS = "ON"
QTMATERIAL3_BUILD_TESTS = "OFF"
QTMATERIAL3_BUILD_EXAMPLES = "OFF"
QTMATERIAL3_BUILD_BENCHMARKS = "OFF"
QTMATERIAL3_BUILD_DESIGNER_PLUGIN = "OFF"
QTMATERIAL3_INSTALL = "OFF"
BUILD_SHARED_LIBS = "OFF"
CMAKE_POSITION_INDEPENDENT_CODE = "ON"
