#!/usr/bin/env python3
# Generated by apply_architecture_gate_integration.py
from __future__ import annotations

import argparse
import json
import re
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


CPP_EXTENSIONS = {
    ".c", ".cc", ".cpp", ".cxx",
    ".h", ".hh", ".hpp", ".hxx",
    ".inl", ".ipp", ".tpp",
}
INCLUDE_RE = re.compile(
    r'^\s*#\s*include\s*[<"]([^>"]+)[>"]',
    re.MULTILINE,
)


class ConfigurationError(RuntimeError):
    pass


@dataclass(frozen=True)
class Violation:
    rule: str
    path: str
    line: int
    message: str


def read_text(path: Path) -> str:
    data = path.read_bytes()
    if data.startswith(b"\xef\xbb\xbf"):
        return data[3:].decode("utf-8")
    if data.startswith(b"\xff\xfe"):
        return data[2:].decode("utf-16-le")
    if data.startswith(b"\xfe\xff"):
        return data[2:].decode("utf-16-be")
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError:
        return data.decode("cp1252")


def line_of(text: str, offset: int) -> int:
    return text.count("\n", 0, max(offset, 0)) + 1


def compile_regex(expression: str, rule: str):
    try:
        return re.compile(
            expression,
            re.MULTILINE | re.DOTALL,
        )
    except re.error as error:
        raise ConfigurationError(
            f"{rule}: invalid regex {expression!r}: {error}"
        ) from error


def safe_path(root: Path, relative: str) -> Path:
    path = (root / relative).resolve()
    try:
        path.relative_to(root)
    except ValueError as error:
        raise ConfigurationError(
            f"path escapes repository root: {relative}"
        ) from error
    return path


def cpp_files(path: Path):
    if not path.exists():
        return
    if path.is_file():
        if path.suffix.lower() in CPP_EXTENSIONS:
            yield path
        return

    ignored = {
        ".git", "build", "_build",
        "cmake-build-debug",
        "cmake-build-release",
    }
    for candidate in sorted(path.rglob("*")):
        if not candidate.is_file():
            continue
        if candidate.suffix.lower() not in CPP_EXTENSIONS:
            continue
        if any(part in ignored for part in candidate.parts):
            continue
        yield candidate


def check_layer(root: Path, rule: dict):
    name = str(rule.get("name", "<unnamed>"))
    prefixes = [
        str(item).replace("\\", "/")
        for item in rule.get(
            "forbidden_include_prefixes",
            [],
        )
    ]
    exact = [
        str(item)
        for item in rule.get("forbidden_includes", [])
    ]

    violations = []
    for configured in rule.get("paths", []):
        directory = safe_path(root, str(configured))
        for path in cpp_files(directory):
            text = read_text(path)
            relative = path.relative_to(root).as_posix()
            for match in INCLUDE_RE.finditer(text):
                include = match.group(1).replace("\\", "/")
                basename = include.rsplit("/", 1)[-1]
                forbidden = (
                    any(include.startswith(prefix) for prefix in prefixes)
                    or any(
                        include == item or basename == item
                        for item in exact
                    )
                )
                if forbidden:
                    violations.append(
                        Violation(
                            name,
                            relative,
                            line_of(text, match.start()),
                            f"forbidden include dependency: {include}",
                        )
                    )
    return violations


def load_files(root: Path, rule: dict):
    name = str(rule.get("name", "<unnamed>"))
    configured = rule.get("files")
    if configured is None:
        single = rule.get("file")
        configured = [] if single is None else [single]
    if not isinstance(configured, list) or not configured:
        raise ConfigurationError(
            f"{name}: rule must define file or files"
        )

    loaded = []
    for item in configured:
        relative = str(item)
        path = safe_path(root, relative)
        if not path.is_file():
            raise ConfigurationError(
                f"{name}: missing configured file: {relative}"
            )
        loaded.append((relative, read_text(path)))
    return loaded


def check_file_rule(root: Path, rule: dict):
    name = str(rule.get("name", "<unnamed>"))
    files = load_files(root, rule)
    violations = []

    for expression in rule.get("forbidden_regex", []):
        expression = str(expression)
        pattern = compile_regex(expression, name)
        for relative, text in files:
            for match in pattern.finditer(text):
                violations.append(
                    Violation(
                        name,
                        relative,
                        line_of(text, match.start()),
                        f"forbidden pattern matched: {expression}",
                    )
                )

    combined = "".join(
        f"\n/* architecture-file: {relative} */\n{text}"
        for relative, text in files
    )
    fallback = files[0][0]

    for expression in rule.get("required_regex", []):
        expression = str(expression)
        if compile_regex(expression, name).search(combined):
            continue
        violations.append(
            Violation(
                name,
                fallback,
                1,
                f"required pattern is missing: {expression}",
            )
        )

    return violations


def check_tree_rule(root: Path, rule: dict):
    name = str(rule.get("name", ""))
    configured_paths = rule.get("paths", [])
    excluded_values = rule.get("exclude_paths", [])
    if not isinstance(configured_paths, list) or not configured_paths:
        raise ConfigurationError(
            f"{name}: tree rule must define a non-empty paths array"
        )
    if not isinstance(excluded_values, list):
        raise ConfigurationError(f"{name}: exclude_paths must be an array")

    excluded = {
        str(value).replace("\\", "/")
        for value in excluded_values
    }
    patterns = [
        (str(expression), compile_regex(str(expression), name))
        for expression in rule.get("forbidden_regex", [])
    ]

    violations = []
    for configured in configured_paths:
        directory = safe_path(root, str(configured))
        for path in cpp_files(directory):
            relative = path.relative_to(root).as_posix()
            if relative in excluded:
                continue
            text = read_text(path)
            for expression, pattern in patterns:
                for match in pattern.finditer(text):
                    violations.append(
                        Violation(
                            name,
                            relative,
                            line_of(text, match.start()),
                            f"forbidden pattern matched: {expression}",
                        )
                    )
    return violations

def load_rules(path: Path):
    try:
        document = json.loads(read_text(path))
    except json.JSONDecodeError as error:
        raise ConfigurationError(
            f"invalid JSON in {path}: {error}"
        ) from error

    if not isinstance(document, dict):
        raise ConfigurationError("rules root must be an object")
    if document.get("schema_version") != 1:
        raise ConfigurationError(
            "only architecture schema_version 1 is supported"
        )
    for key in ("layer_rules", "tree_rules", "file_rules", "text_rules"):
        if not isinstance(document.get(key, []), list):
            raise ConfigurationError(f"{key} must be an array")
    return document


def rule_names(document: dict):
    names = []
    for category in ("layer_rules", "tree_rules", "file_rules", "text_rules"):
        for rule in document.get(category, []):
            names.append(str(rule.get("name", "<unnamed>")))
    return names


def run_checks(root: Path, document: dict, selected=None):
    violations = []

    def enabled(rule):
        return (
            selected is None
            or str(rule.get("name", "<unnamed>")) in selected
        )

    for rule in document.get("layer_rules", []):
        if enabled(rule):
            violations.extend(check_layer(root, rule))
    for rule in document.get("tree_rules", []):
        if enabled(rule):
            violations.extend(check_tree_rule(root, rule))
    for category in ("file_rules", "text_rules"):
        for rule in document.get(category, []):
            if enabled(rule):
                violations.extend(check_file_rule(root, rule))

    return sorted(
        violations,
        key=lambda item: (
            item.path,
            item.line,
            item.rule,
            item.message,
        ),
    )


def print_violation(item: Violation, output_format: str):
    if output_format == "github":
        message = (
            f"[{item.rule}] {item.message}"
            .replace("%", "%25")
            .replace("\r", "%0D")
            .replace("\n", "%0A")
        )
        print(
            f"::error file={item.path},line={item.line}::{message}"
        )
    else:
        print(
            f"{item.path}:{item.line}: "
            f"error [{item.rule}]: {item.message}"
        )


def self_test():
    with tempfile.TemporaryDirectory(
        prefix="qtm3-architecture-"
    ) as temporary:
        root = Path(temporary)
        (root / "include/foundation").mkdir(parents=True)
        (root / "src/widget").mkdir(parents=True)
        (root / "include/foundation/value.h").write_text(
            "#include <QWidget>\n",
            encoding="utf-8",
        )
        (root / "src/widget/widget.h").write_text(
            "class RuntimeSpec {};\n",
            encoding="utf-8",
        )
        (root / "src/widget/widget.cpp").write_text(
            "void dedicatedResolver() {}\n",
            encoding="utf-8",
        )

        document = {
            "schema_version": 1,
            "layer_rules": [
                {
                    "name": "layer",
                    "paths": ["include/foundation"],
                    "forbidden_includes": ["QWidget"],
                }
            ],
            "file_rules": [
                {
                    "name": "aggregate",
                    "files": [
                        "src/widget/widget.h",
                        "src/widget/widget.cpp",
                    ],
                    "required_regex": [
                        r"\bRuntimeSpec\b",
                        r"\bdedicatedResolver\s*\(",
                    ],
                    "forbidden_regex": [r"\bSpecFactory\b"],
                }
            ],
            "text_rules": [],
        }

        violations = run_checks(root.resolve(), document)
        assert len(violations) == 1
        assert violations[0].rule == "layer"
        assert violations[0].line == 1

        (root / "include/foundation/value.h").write_text(
            "#pragma once\n",
            encoding="utf-8",
        )
        assert not run_checks(root.resolve(), document)

    print("architecture checker self-test: OK")


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--rules", type=Path)
    parser.add_argument(
        "--format",
        choices=("text", "github"),
        default="text",
    )
    parser.add_argument("--rule", action="append", default=[])
    parser.add_argument("--list-rules", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    return parser.parse_args()


def main():
    args = parse_args()
    if args.self_test:
        self_test()
        return 0

    root = args.root.resolve()
    rules = (
        args.rules.resolve()
        if args.rules
        else (
            root
            / "scripts/architecture/architecture_rules.json"
        ).resolve()
    )
    if not root.is_dir():
        raise ConfigurationError(
            f"repository root does not exist: {root}"
        )
    if not rules.is_file():
        raise ConfigurationError(
            f"architecture rules file does not exist: {rules}"
        )

    document = load_rules(rules)
    names = rule_names(document)

    if args.list_rules:
        print("\n".join(names))
        return 0

    selected = set(args.rule) if args.rule else None
    if selected is not None:
        unknown = sorted(selected - set(names))
        if unknown:
            raise ConfigurationError(
                "unknown rule names: " + ", ".join(unknown)
            )

    violations = run_checks(root, document, selected)
    for item in violations:
        print_violation(item, args.format)

    if violations:
        print(
            f"architecture check: FAILED "
            f"({len(violations)} violation(s))"
        )
        return 1

    count = len(selected) if selected is not None else len(names)
    print(f"architecture check: OK ({count} rule(s))")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ConfigurationError as error:
        print(
            f"architecture checker configuration error: {error}",
            file=sys.stderr,
        )
        raise SystemExit(2)
