find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Widgets)

if(COMMAND qt_add_executable)
    qt_add_executable(qtmaterial3_dashboard_demo
        main.cpp
        dashboardaccountpage.cpp
        dashboardaccountpage.h
        dashboardaccountpage.ui
        dashboardaccountpanel.cpp
        dashboardaccountpanel.h
        dashboardaccountpanel.ui
        dashboardcontactspanel.cpp
        dashboardcontactspanel.h
        dashboardcontactspanel.ui
        dashboardnotificationspanel.cpp
        dashboardnotificationspanel.h
        dashboardnotificationspanel.ui
        dashboardsettingspanel.cpp
        dashboardsettingspanel.h
        dashboardsettingspanel.ui
        dashboardcontactspanel.cpp
        dashboardcontactspanel.h
        dashboardcontactspanel.ui
        dashboardnotificationspanel.cpp
        dashboardnotificationspanel.h
        dashboardnotificationspanel.ui
        dashboardsettingspanel.cpp
        dashboardsettingspanel.h
        dashboardsettingspanel.ui
        dashboardwindow.cpp
        dashboardwindow.h
        dashboardwindow.ui
        dashboardcharts.cpp
        dashboardcharts.h
    )
else()
    add_executable(qtmaterial3_dashboard_demo
        main.cpp
        dashboardaccountpage.cpp
        dashboardaccountpage.h
        dashboardaccountpage.ui
        dashboardaccountpanel.cpp
        dashboardaccountpanel.h
        dashboardaccountpanel.ui
        dashboardwindow.cpp
        dashboardwindow.h
        dashboardwindow.ui
        dashboardcharts.cpp
        dashboardcharts.h
    )
endif()

target_link_libraries(qtmaterial3_dashboard_demo
    PRIVATE
        Qt${QT_VERSION_MAJOR}::Widgets
        qtmaterial3_theme_model
        qtmaterial3_theme_runtime
        qtmaterial3_core
        qtmaterial3_specs
        qtmaterial3_effects
        qtmaterial3_widgets
)
