find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Widgets)

set(QTMATERIAL3_DASHBOARD_SOURCES
    main.cpp
    dashboardaccountpage.cpp
    dashboardaccountpage.h
    dashboardaccountpage.ui
    dashboardaccountpanel.cpp
    dashboardaccountpanel.h
    dashboardaccountpanel.ui
    dashboardcontactspanel.cpp
    dashboardcontactspanel.h
    dashboardcontactspanel.ui
    dashboardnotificationspanel.cpp
    dashboardnotificationspanel.h
    dashboardnotificationspanel.ui
    dashboardsettingspanel.cpp
    dashboardsettingspanel.h
    dashboardsettingspanel.ui
    dashboardecommercepage.cpp
    dashboardecommercepage.h
    dashboardecommercepage.ui
    dashboardinvoicepage.cpp
    dashboardinvoicepage.h
    dashboardinvoicepage.ui
    dashboardappspage.cpp
    dashboardappspage.h
    dashboardappspage.ui
    dashboardprojectspage.cpp
    dashboardprojectspage.h
    dashboardprojectspage.ui
    dashboardwindow.cpp
    dashboardwindow.h
    dashboardwindow.ui
    dashboardherobanners.cpp
    dashboardherobanners.h
    dashboardcharts.cpp
    dashboardcharts.h
    dashboarddemostyle.cpp
    dashboarddemostyle.h
)

if(COMMAND qt_add_executable)
    qt_add_executable(qtmaterial3_dashboard_demo
        ${QTMATERIAL3_DASHBOARD_SOURCES}
    )
else()
    add_executable(qtmaterial3_dashboard_demo
        ${QTMATERIAL3_DASHBOARD_SOURCES}
    )
endif()

target_link_libraries(qtmaterial3_dashboard_demo
    PRIVATE
        Qt${QT_VERSION_MAJOR}::Widgets
        qtmaterial3_theme_model
        qtmaterial3_theme_runtime
        qtmaterial3_core
        qtmaterial3_specs
        qtmaterial3_effects
        qtmaterial3_widgets
)
