#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
TOOLS = ROOT / "tools"
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))

from component_registry import (  # noqa: E402
    AXES,
    AXIS_LABELS,
    BUTTON_IDS,
    MATURITY_ORDER,
    RegistryError,
    axis_md,
    derived_maturity,
    effective_maturity,
    load_registry,
    sort_key,
    validate_registry,
)

ROOT_STATUS = ROOT / "STATUS.md"
DOC_STATUS = ROOT / "docs" / "component-status.md"
MATURITY_DOC = ROOT / "docs" / "components" / "maturity.md"
def group_by_family(components: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for item in sorted(components, key=sort_key):
        grouped[str(item.get("family", "Other"))].append(item)
    return grouped


def render_root_status(components: list[dict[str, Any]]) -> str:
    counts = Counter(effective_maturity(item) for item in components)
    total = len(components)

    lines = [
        "# Project Status",
        "",
        "> Generated from `docs/components/component-registry.json` by `scripts/generate_component_status.py`.",
        "> Do not edit this file directly.",
        "",
        "## Component maturity summary",
        "",
        f"Total tracked components: **{total}**.",
        "",
        "| Maturity | Count |",
        "|---|---:|",
    ]

    for maturity in MATURITY_ORDER:
        lines.append(f"| `{maturity}` | {counts[maturity]} |")

    lines.extend([
        "",
        "## Release blockers",
        "",
    ])

    blockers = [
        item for item in components
        if bool(item.get("releaseScope", True)) and effective_maturity(item) in {"skeleton", "planned"}
    ]

    if blockers:
        for item in sorted(blockers, key=sort_key):
            lines.append(f"- `{item.get('id')}` — {item.get('name')} is `{effective_maturity(item)}`.")
    else:
        lines.append("No registry-level maturity blockers.")

    lines.extend([
        "",
        "## Generated documents",
        "",
        "- `docs/component-status.md` — compact component registry status.",
        "- `docs/components/maturity.md` — detailed maturity matrix.",
        "",
    ])

    return "\n".join(lines).rstrip() + "\n"


def render_component_status(components: list[dict[str, Any]]) -> str:
    grouped = group_by_family(components)

    lines = [
        "# Component status",
        "",
        "> Generated from `docs/components/component-registry.json` by `scripts/generate_component_status.py`.",
        "> Do not edit this file directly.",
        "",
        "Maturity levels: `complete`, `usable`, `partial`, `skeleton`, `planned`.",
        "",
    ]

    for family in sorted(grouped):
        lines.append(f"## {family}")
        lines.append("")
        lines.append("| ID | Component | Maturity | Header | Spec | Test | Docs | Gallery |")
        lines.append("|---|---|---:|---|---|---|---|---|")

        for item in grouped[family]:
            lines.append(
                "| `{id}` | {name} | `{maturity}` | `{header}` | `{spec}` | `{test}` | `{docs}` | `{gallery}` |".format(
                    id=item.get("id", ""),
                    name=item.get("name", ""),
                    maturity=effective_maturity(item),
                    header=item.get("publicHeader", ""),
                    spec=item.get("specType", ""),
                    test=item.get("testTarget", ""),
                    docs=item.get("docsPath", ""),
                    gallery=item.get("galleryRoute", ""),
                )
            )

        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def first_note(item: dict[str, Any]) -> str:
    axes = item.get("maturityAxes")
    if not isinstance(axes, dict):
        return ""

    gaps = axes.get("gaps")
    if isinstance(gaps, list) and gaps:
        return str(gaps[0])

    actions = axes.get("nextActions")
    if isinstance(actions, list) and actions:
        return str(actions[0])

    return ""


def render_not_evaluated_summary(components: list[dict[str, Any]]) -> list[str]:
    counts: Counter[str] = Counter()

    for item in components:
        axes = item.get("maturityAxes")
        if not isinstance(axes, dict):
            for axis in AXES:
                counts[axis] += 1
            continue

        for axis in AXES:
            if axes.get(axis) is None:
                counts[axis] += 1

    lines = [
        "## Not evaluated axes",
        "",
        "| Axis | Count |",
        "|---|---:|",
    ]

    for axis in AXES:
        lines.append(f"| {AXIS_LABELS[axis]} | {counts[axis]} |")

    lines.append("")
    return lines


def render_next_actions(components: list[dict[str, Any]]) -> list[str]:
    rows: list[tuple[str, str]] = []

    for item in sorted(components, key=sort_key):
        axes = item.get("maturityAxes")
        if not isinstance(axes, dict):
            continue

        actions = axes.get("nextActions")
        if not isinstance(actions, list):
            continue

        for action in actions:
            rows.append((str(item.get("name", "")), str(action)))

    lines = [
        "## Next actions",
        "",
        "| Component | Action |",
        "|---|---|",
    ]

    if rows:
        for component, action in rows:
            lines.append(f"| {component} | {action} |")
    else:
        lines.append("| — | No next actions declared. |")

    lines.append("")
    return lines


def render_button_completion_gate(components: list[dict[str, Any]]) -> list[str]:
    by_id = {str(item.get("id", "")): item for item in components}

    lines = [
        "## Buttons completion gate",
        "",
        "The Buttons family can be considered `complete` only when all eight public variants are tracked and every required axis is evaluated.",
        "",
        "| Button | Tracked | Status | Missing axes |",
        "|---|---:|---:|---|",
    ]

    for cid in sorted(BUTTON_IDS):
        item = by_id.get(cid)
        if item is None:
            lines.append(f"| `{cid}` | no | — | all |")
            continue

        axes = item.get("maturityAxes")
        missing = []
        if not isinstance(axes, dict):
            missing = AXES[:]
        else:
            for axis in AXES:
                if axes.get(axis) is None:
                    missing.append(axis)

        lines.append(
            f"| `{cid}` | yes | `{effective_maturity(item)}` | {', '.join(missing) if missing else '—'} |"
        )

    lines.append("")
    return lines


def render_maturity_doc(components: list[dict[str, Any]]) -> str:
    grouped = group_by_family(components)

    lines = [
        "# Component Maturity Matrix",
        "",
        "> Generated from `docs/components/component-registry.json` by `scripts/generate_component_status.py`.",
        "> Do not edit this file directly.",
        "",
        "## Legend",
        "",
        "| Value | Meaning |",
        "|---|---|",
        "| `0` | Not started |",
        "| `1` | Prototype, scaffold, or incomplete implementation |",
        "| `2` | Usable in simple cases, with known gaps |",
        "| `3` | Functional, coherent, and reasonably covered |",
        "| `4` | Robust, documented, tested, and consistent |",
        "| `?` | Not evaluated yet |",
        "| `N/A` | Not applicable |",
        "",
        "## Matrix",
        "",
    ]

    header = "| ID | Component | Status | " + " | ".join(AXIS_LABELS[axis] for axis in AXES) + " | Notes |"
    separator = "|---|---|---:|" + "|".join("---:" for _ in AXES) + "|---|"

    for family in sorted(grouped):
        lines.append(f"### {family}")
        lines.append("")
        lines.append(header)
        lines.append(separator)

        for item in grouped[family]:
            axes = item.get("maturityAxes")
            if not isinstance(axes, dict):
                axes = {}

            axis_cells = " | ".join(axis_md(axes.get(axis)) for axis in AXES)
            lines.append(
                f"| `{item.get('id', '')}` | {item.get('name', '')} | `{effective_maturity(item)}` | {axis_cells} | {first_note(item)} |"
            )

        lines.append("")

    lines.extend(render_button_completion_gate(components))
    lines.extend(render_not_evaluated_summary(components))
    lines.extend(render_next_actions(components))

    return "\n".join(lines).rstrip() + "\n"


def write_or_check(path: Path, content: str, *, check: bool) -> bool:
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == content:
            return True

        rel = path.relative_to(ROOT)
        print(f"{rel} is out of date")
        for line in difflib.unified_diff(
            current.splitlines(),
            content.splitlines(),
            fromfile=f"{rel} current",
            tofile=f"{rel} generated",
            lineterm="",
        ):
            print(line)
        return False

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate component registry artifacts and maturity documents.")
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    parser.add_argument("--strict", action="store_true", help="treat registry warnings as errors")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)

    try:
        components = load_registry()
    except RegistryError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    errors, warnings = validate_registry(components, strict=args.strict)

    if warnings:
        print("component registry warnings:")
        for warning in warnings:
            print(f" - {warning}")

    if errors:
        print("component registry validation failed:")
        for error in errors:
            print(f" - {error}")
        return 1

    outputs = {
        ROOT_STATUS: render_root_status(components),
        DOC_STATUS: render_component_status(components),
        MATURITY_DOC: render_maturity_doc(components),
    }

    ok = True
    for path, content in outputs.items():
        ok &= write_or_check(path, content, check=args.check)

    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
