# Generated by apply_architecture_gate_integration.py
include_guard(GLOBAL)

function(qtmaterial3_add_architecture_guard)
    if(NOT BUILD_TESTING)
        return()
    endif()

    find_package(Python3 COMPONENTS Interpreter QUIET)
    if(NOT Python3_Interpreter_FOUND)
        message(
            WARNING
            "Python3 was not found; architecture tests are disabled."
        )
        return()
    endif()

    set(
        _qtm3_architecture_checker
        "${CMAKE_SOURCE_DIR}/scripts/architecture/check_architecture.py"
    )
    set(
        _qtm3_architecture_rules
        "${CMAKE_SOURCE_DIR}/scripts/architecture/architecture_rules.json"
    )

    if(NOT EXISTS "${_qtm3_architecture_checker}")
        message(
            FATAL_ERROR
            "Architecture checker is missing: "
            "${_qtm3_architecture_checker}"
        )
    endif()
    if(NOT EXISTS "${_qtm3_architecture_rules}")
        message(
            FATAL_ERROR
            "Architecture rules are missing: "
            "${_qtm3_architecture_rules}"
        )
    endif()

    add_test(
        NAME tst_architecture_checker_selftest
        COMMAND
            "${Python3_EXECUTABLE}"
            "${_qtm3_architecture_checker}"
            --self-test
    )
    add_test(
        NAME tst_architecture_rules
        COMMAND
            "${Python3_EXECUTABLE}"
            "${_qtm3_architecture_checker}"
            --root "${CMAKE_SOURCE_DIR}"
            --rules "${_qtm3_architecture_rules}"
    )
    set_tests_properties(
        tst_architecture_checker_selftest
        tst_architecture_rules
        PROPERTIES LABELS "architecture"
    )
endfunction()
