// Widget-side linker fallback for data component default specs.
// Generated by fix-widget-link-datacomponent-spec-defaults.sh.
//
// Why this exists:
//   qtmaterialdatepicker.cpp, qtmaterialtable.cpp, qtmaterialgridlist.cpp and
//   qtmaterialcarousel.cpp call default*Spec() functions. In the current split
//   build, the real functions are compiled into the Specs target, but they are
//   not visible to the Widgets target on MSVC. This file provides the missing
//   definitions in the Widgets target without adding duplicate symbols to the
//   Specs target.

#include <qtmaterial/specs/qtmaterialdatacomponentspecs.h>

namespace QtMaterial {

DatePickerSpec defaultDatePickerSpec()
{
    DatePickerSpec spec;
    return spec;
}

TableSpec defaultTableSpec()
{
    TableSpec spec;
    return spec;
}

GridListSpec defaultGridListSpec()
{
    GridListSpec spec;
    return spec;
}

CarouselSpec defaultCarouselSpec()
{
    CarouselSpec spec;
    return spec;
}

} // namespace QtMaterial
